### ISSUE TITLE
Build file looking for ./src directory

### ISSUE THREAD

**Issue by shivika** [kevinjhanna/input-autocomplete#3]
Hi, I just installed this package and tried to run it, but the index.js file in the build directory is looking for a file in a src directory that did not get installed with the package ("./src/InputAutocomplete).

**Comment by kevinjhanna** [comment]
Sorry! I was trying to reduce the npm package distribution by ignoring `src` directory. It seems it ignored not only `./src` but also `./build/src`.

I've just published v1.0.5 with this fix.

**Comment by shivika** [comment]
Thanks for the quick turnaround!
